apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::653611014156:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-VURUU1VM6J3E
      username: system:node:{{EC2PrivateDNSName}}
      - system:masters
      rolearn: arn:aws:iam::653611014156:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-11T06:47:01Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "4981"
  uid: 44e3767f-a3d3-4a96-9350-a35d936c4749
