apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::653611014156:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-5QAIA8R16ZR0
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::653611014156:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-11T21:35:12Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1803"
  uid: 12de864f-c984-4682-8fab-89dbb126c4ff
